permissions:
  contents: write

# …
- name: Install dependencies
  run: npm install

- name: Build site
  run: npm run build

- name: Deploy to Pages
  uses: peaceiris/actions-gh-pages@v4
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./dist
